"""SPEC-U2 report: compose pipelines per item from router and gate outputs, run the registered tests.

    python scripts/u2_report.py

Reads results/u2/<arm>/{route,gate}.jsonl; writes reports/ubench/u2.md.
"""

from __future__ import annotations

import json
import math

import _bootstrap  # noqa: F401
from jevq.config import ROOT
from jevq.xbench import u2_joint as u
from jevq.xbench.stats import holm, wilson

RUNS = ROOT / "results" / "u2"
OUT = ROOT / "reports" / "ubench"
SEEDS = (0, 1, 2)

# name -> (router arm, gate arm); "{s}" is replaced by the seed suffix for seeded Jev arms.
PIPELINES = {
    "A": ("J-V0", "TRM-cv", "generic small Qwen (Qwen3.5-4B-Base) picks, TRM gate decides"),
    "A2": ("Bonsai-8B", "TRM-cv", "Bonsai-8B (1-bit Qwen-family LLM) picks, TRM gate decides"),
    "B": ("SkillRouter-TRM", "TRM-cv", "TRM router picks, TRM gate decides"),
    "C": ("J-multi{s}", "J-multi{s}", "Jev (J-multi) picks and decides"),
    "C-loop": ("J-multi-loop{s}-r2", "J-multi-loop{s}-r2", "looped Jev picks and decides"),
    "D": ("J-V0", "J-V0", "generic small Qwen picks and decides"),
    "H": ("J-multi{s}", "TRM-cv", "Jev picks, TRM gate decides"),
    "E": ("lexical-router", "script", "lexical router picks, registered rule decides (ceiling)"),
}


def seed_suffix(seed: int) -> str:
    return "" if seed == 0 else f"-s{seed}"


def load_arm(arm: str, kind: str) -> dict[str, dict] | None:
    path = RUNS / arm / f"{kind}.jsonl"
    if not path.exists():
        return None
    return {r["item_id"]: r for r in map(json.loads, path.read_text(encoding="utf-8").splitlines())}


def outcomes(items, router: str, gate: str) -> dict[str, dict] | None:
    """Per item end-to-end outcome for one pipeline, or None if a run is missing."""
    route, gates = load_arm(router, "route"), load_arm(gate, "gate")
    if route is None or gates is None:
        return None
    return {i["item_id"]: u.end_to_end(i, route[i["item_id"]]["pred"],
                                       gates[i["item_id"]]["pred"] if i["kind"] == "joint" else None) for i in items}


def instances(items, name: str) -> list[tuple[int, dict]]:
    """(seed, outcomes) for every available instance of a pipeline: seeds for Jev pipelines, one otherwise."""
    router, gate, _ = PIPELINES[name]
    seeds = SEEDS if "{s}" in router + gate else (0,)
    out = []
    for seed in seeds:
        res = outcomes(items, router.format(s=seed_suffix(seed)), gate.format(s=seed_suffix(seed)))
        if res is not None:
            out.append((seed, res))
    return out


def binom_tail(k: int, n: int) -> float:
    return 1.0 if n == 0 else sum(math.comb(n, i) for i in range(k, n + 1)) / 2 ** n


def pooled(a_list, b_list) -> dict:
    """Discordant (instance, item) pairs; a single-instance arm is paired with every instance of the other."""
    pairs = [(a, b) for (sa, a) in a_list for (sb, b) in b_list if len(a_list) == 1 or len(b_list) == 1 or sa == sb]
    a_only = sum(a[i]["success"] and not b[i]["success"] for a, b in pairs for i in a)
    b_only = sum(b[i]["success"] and not a[i]["success"] for a, b in pairs for i in a)
    n = a_only + b_only
    one = binom_tail(a_only, n)
    two = min(1.0, 2 * min(binom_tail(a_only, n), binom_tail(b_only, n)))
    return {"a_only": a_only, "b_only": b_only, "p_one_sided": one, "p_two_sided": two, "pairs": len(pairs)}


def rate(res_list, key: str, kinds=None) -> tuple[int, int]:
    k = n = 0
    for _, res in res_list:
        for item_id, r in res.items():
            if kinds and item_id.split(".")[1] not in kinds:
                continue
            k += bool(r[key])
            n += 1
    return k, n


def fmt_rate(k: int, n: int) -> str:
    if not n:
        return "-"
    low, high = wilson(k, n)
    return f"{k / n:.3f} [{low:.2f}, {high:.2f}]"


def render(items) -> str:
    inst = {name: instances(items, name) for name in PIPELINES}
    lines = ["# SPEC-U2 report: end-to-end skill pipelines", "",
             "Generated by `scripts/u2_report.py` from `results/u2`. Registration: `docs/ubench/SPEC-U2.md`. "
             f"Items: {len(items)} (360 joint, 150 confusable, 90 negative). Rates pool every available seed of a pipeline; "
             "intervals are Wilson 95% on the pooled count.", "",
             "## Registered tests", "", "| Test | Claim | Result | Status |", "|---|---|---|---|"]
    tests = {"T1": ("C", "A", "one", "Jev pipeline beats generic Qwen picking a TRM skill"),
             "T2": ("B", "C", "two", "TRM pipeline differs from the Jev pipeline (two-sided)"),
             "T3": ("C", "D", "one", "Jev pipeline beats generic Qwen doing both steps")}
    results, ps = {}, {}
    for key, (a, b, sided, claim) in tests.items():
        if not inst[a] or not inst[b]:
            results[key] = None
            continue
        r = pooled(inst[a], inst[b])
        results[key] = r
        ps[key] = r["p_one_sided"] if sided == "one" else r["p_two_sided"]
    decided = all(r is not None for r in results.values()) and len(inst["C"]) == 3
    adjusted = holm(ps) if decided else {}
    for key, (a, b, sided, claim) in tests.items():
        r = results[key]
        if r is None:
            lines.append(f"| {key} | {claim} | - | pending |")
            continue
        p = r["p_one_sided"] if sided == "one" else r["p_two_sided"]
        holm_text = f", Holm p = {adjusted[key]:.3g}" if key in adjusted else ""
        status = "decided" if decided else f"interim ({len(inst['C'])} of 3 Jev seeds)"
        lines.append(f"| {key} | {claim} | {a}-only {r['a_only']} vs {b}-only {r['b_only']}, p = {p:.3g}{holm_text} | {status} |")

    lines += ["", "## Pipelines", "",
              "| Pipeline | Router -> gate | Instances | End-to-end success | Unsafe | Route ok (joint) | Route ok (confusable) | Route ok (negative) |",
              "|---|---|---|---|---|---|---|---|"]
    for name, (router, gate, desc) in PIPELINES.items():
        res = inst[name]
        if not res:
            lines.append(f"| {name} | {desc} | 0 | pending | | | | |")
            continue
        cells = [fmt_rate(*rate(res, "success")), fmt_rate(*rate(res, "unsafe"))]
        cells += [fmt_rate(*rate(res, "route_ok", {kind})) for kind in ("joint", "confusable", "negative")]
        lines.append(f"| {name} | {desc} | {len(res)} | " + " | ".join(cells) + " |")

    lines += ["", "## Gate accuracy on all 360 joint gate states (whatever the router did)", "", "| Gate | Accuracy | Unsafe commits |", "|---|---|---|"]
    for gate in ["script", "kNN-critic", "TRM-cv", "J-V0", "J-multi", "J-multi-s1", "J-multi-s2", "J-multi-loop-r2", "J-multi-loop-s1-r2", "J-multi-loop-s2-r2"]:
        g = load_arm(gate, "gate")
        if g is None:
            continue
        joint = [i for i in items if i["kind"] == "joint"]
        k = sum(g[i["item_id"]]["pred"] == i["gold_gate"] for i in joint)
        uns = sum(g[i["item_id"]]["pred"] == "commit" and i["gold_gate"] == "reject_or_abstain" for i in joint)
        lines.append(f"| {gate} | {fmt_rate(k, len(joint))} | {uns}/{sum(i['gold_gate'] == 'reject_or_abstain' for i in joint)} |")
    return "\n".join(lines) + "\n"


def main() -> None:
    items = u.build_items()
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "u2.md").write_text(render(items), encoding="utf-8")
    print(f"wrote {OUT / 'u2.md'}")


if __name__ == "__main__":
    main()
