"""SPEC-U4 report: Campsite repair head-to-head (Part D deciders, Part G repairers).

    python scripts/u4_report.py

Reads results/u4/{decide,repair}/<record>.jsonl; writes reports/ubench/u4.md.
"""

from __future__ import annotations

import json
import statistics

import _bootstrap  # noqa: F401
import u2_report as u2r
from jevq.config import ROOT
from jevq.xbench import u4_campsite as u
from jevq.xbench.stats import holm, wilson

RUNS = ROOT / "results" / "u4"
OUT = ROOT / "reports" / "ubench"
SEEDS = (0, 1, 2)

DECIDERS = {
    "J-V0": ("J-V0", "generic small Qwen (Qwen3.5-4B-Base)"),
    "J-multi": ("J-multi{s}", "Jev (J-multi)"),
    "J-multi-loop": ("J-multi-loop{s}-r2", "looped Jev, 2 passes"),
    "Decision-TRM": ("Decision-TRM{s}", "TinyRecursivePolicy structure, trained on U4 train"),
    "always-commit": ("always-commit", "rule"),
    "c_repair_if_c_fail": ("c_repair_if_c_fail", "Hermes-Skills flow policy"),
    "dual_repair_if_any_sig_fail": ("dual_repair_if_any_sig_fail", "Hermes-Skills flow policy"),
    "menu-ceiling": ("menu-ceiling", "best action with post-repair verification (ceiling)"),
    "CSP-resolve": ("CSP-resolve", "discard the candidate and solve (ceiling)"),
}
REPAIRERS = {
    "identity": ("identity", "no repair"),
    "c_repair": ("c_repair", "Hermes-Skills c_only_projection"),
    "dual_repair": ("dual_repair", "Hermes-Skills dual_signature_projection"),
    "J-V0": ("J-V0", "generic small Qwen writes the grid"),
    "J-multi": ("J-multi{s}", "Jev writes the grid"),
    "CSP-resolve": ("CSP-resolve", "CSP solver (ceiling)"),
}
TESTS = {
    "D1": ("decide", "J-multi", "Decision-TRM", "two", "Jev decider vs Decision-TRM (two-sided)"),
    "D2": ("decide", "J-multi", "J-V0", "one", "Jev decider beats the generic small Qwen"),
    "G1": ("repair", "J-multi", "dual_repair", "two", "Jev-written repair vs dual_repair (two-sided)"),
}


def suffix(seed: int) -> str:
    return "" if seed == 0 else f"-s{seed}"


def load(part: str, record: str) -> dict[str, dict] | None:
    path = RUNS / part / f"{record}.jsonl"
    if not path.exists():
        return None
    return {r["item_id"]: r for r in map(json.loads, path.read_text(encoding="utf-8").splitlines())}


def instances(part: str, arm: str) -> list[tuple[int, dict]]:
    pattern, _ = (DECIDERS if part == "decide" else REPAIRERS)[arm]
    seeds = SEEDS if "{s}" in pattern else (0,)
    out = []
    for seed in seeds:
        rows = load(part, pattern.format(s=suffix(seed)))
        if rows is not None:
            out.append((seed, rows))
    return out


def rate(inst, key: str, kind: str | None = None) -> tuple[int, int]:
    rows = [r for _, res in inst for r in res.values() if kind is None or r["kind"] == kind]
    return sum(bool(r[key]) for r in rows), len(rows)


def fmt(k: int, n: int, ci: bool = True) -> str:
    if not n:
        return "-"
    if not ci:
        return f"{k / n:.2f}"
    low, high = wilson(k, n)
    return f"{k / n:.3f} [{low:.2f}, {high:.2f}]"


def render() -> str:
    lines = ["# SPEC-U4 report: Campsite repair head-to-head", "",
             "Generated by `scripts/u4_report.py`. Registration: `docs/ubench/SPEC-U4.md`. 480 test items, 60 per candidate type; "
             "rates pool every available seed; intervals are Wilson 95%.", "",
             "## Registered tests", "", "| Test | Claim | Result | Status |", "|---|---|---|---|"]
    results, ps = {}, {}
    for tid, (part, a, b, sided, claim) in TESTS.items():
        ia, ib = instances(part, a), instances(part, b)
        if not ia or not ib:
            results[tid] = None
            continue
        res = u2r.pooled(ia, ib)
        results[tid] = (res, len(ia), len(ib))
        ps[tid] = res["p_one_sided"] if sided == "one" else res["p_two_sided"]
    decided = all(v is not None for v in results.values()) and len(instances("decide", "J-multi")) == 3 \
        and len(instances("repair", "J-multi")) == 3 and len(instances("decide", "Decision-TRM")) == 3
    adjusted = holm(ps) if decided else {}
    for tid, (part, a, b, sided, claim) in TESTS.items():
        if results[tid] is None:
            lines.append(f"| {tid} | {claim} | - | pending |")
            continue
        res, na, nb = results[tid]
        holm_text = f", Holm p = {adjusted[tid]:.3g}" if tid in adjusted else ""
        lines.append(f"| {tid} | {claim} | {a}-only {res['a_only']} vs {b}-only {res['b_only']} ({na} x {nb} instances), "
                     f"p = {ps[tid]:.3g}{holm_text} | {'decided' if decided else 'interim'} |")

    lines += ["", "## Part D: deciders (the committed grid is scored)", "",
              "| Arm | Instances | Success | Unsafe (committed a failing grid) | Rejected | " + " | ".join(u.TYPES) + " |",
              "|---|---|---|---|---|" + "---|" * len(u.TYPES)]
    for arm, (_, desc) in DECIDERS.items():
        inst = instances("decide", arm)
        if not inst:
            lines.append(f"| {arm} ({desc}) | 0 | pending | | |" + " |" * len(u.TYPES))
            continue
        by_kind = [fmt(*rate(inst, "success", k), ci=False) for k in u.TYPES]
        lines.append(f"| {arm} ({desc}) | {len(inst)} | {fmt(*rate(inst, 'success'))} | {fmt(*rate(inst, 'unsafe'))} | "
                     f"{fmt(*rate(inst, 'rejected'), ci=False)} | " + " | ".join(by_kind) + " |")
    lines += ["", "Action mix per decider (share of items):", "", "| Arm | " + " | ".join(u.ACTIONS) + " |", "|---|" + "---|" * len(u.ACTIONS)]
    for arm in DECIDERS:
        inst = instances("decide", arm)
        rows = [r for _, res in inst for r in res.values()]
        if rows and all("action" in r for r in rows):
            lines.append(f"| {arm} | " + " | ".join(f"{sum(r['action'] == a for r in rows) / len(rows):.2f}" for a in u.ACTIONS) + " |")

    lines += ["", "## Part G: repairers (the output grid is scored)", "",
              "| Arm | Instances | Success | Parsed | Mean edits to candidate | " + " | ".join(u.TYPES) + " |",
              "|---|---|---|---|---|" + "---|" * len(u.TYPES)]
    for arm, (_, desc) in REPAIRERS.items():
        inst = instances("repair", arm)
        if not inst:
            lines.append(f"| {arm} ({desc}) | 0 | pending | | |" + " |" * len(u.TYPES))
            continue
        edits = [r["edits_to_candidate"] for _, res in inst for r in res.values() if r["edits_to_candidate"] is not None]
        mean_edits = f"{statistics.mean(edits):.2f}" if edits else "-"
        by_kind = [fmt(*rate(inst, "success", k), ci=False) for k in u.TYPES]
        lines.append(f"| {arm} ({desc}) | {len(inst)} | {fmt(*rate(inst, 'success'))} | {fmt(*rate(inst, 'parsed'), ci=False)} | "
                     f"{mean_edits} | " + " | ".join(by_kind) + " |")
    trm = RUNS / "decide" / "Decision-TRM.json"
    if trm.exists():
        info = json.loads(trm.read_text(encoding="utf-8"))
        lines += ["", f"Decision-TRM (seed 0): {info.get('params_total')} parameters, {info.get('steps_selected')} full-batch steps, "
                  f"val accuracy {info.get('val_accuracy'):.3f}; trained on {info.get('train_items')} items."]
    return "\n".join(lines) + "\n"


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "u4.md").write_text(render(), encoding="utf-8")
    print(f"wrote {OUT / 'u4.md'}")


if __name__ == "__main__":
    main()
